<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>pom-icy</artifactId>
        <groupId>fr.icy</groupId>
        <version>3.0.0-a.7</version>
    </parent>

    <groupId>fr.icy</groupId>
    <artifactId>icy</artifactId>
    <version>3.0.0-a.7</version>

    <name>Icy</name>
    <description>Icy is an open community platform for bioimage informatics</description>
    <url>https://icy.bioimageanalysis.org/</url>
    <inceptionYear>2010</inceptionYear>

    <scm>
        <url>https://gitlab.pasteur.fr/bia/icy/icy</url>
        <tag>v${project.version}</tag>
    </scm>

    <issueManagement>
        <system>GitLab Issues</system>
        <url>https://gitlab.pasteur.fr/bia/icy/icy/-/issues</url>
    </issueManagement>
    <ciManagement>
        <system>GitLab CI</system>
        <url>https://gitlab.pasteur.fr/bia/icy/icy/-/pipelines</url>
    </ciManagement>

    <organization>
        <name>Institut Pasteur</name>
        <url>https://www.pasteur.fr/</url>
    </organization>

    <licenses>
        <license>
            <name>GNU LGPLv3</name>
            <url>https://www.gnu.org/licenses/lgpl-3.0</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>tmusset</id>
            <name>Thomas Musset</name>
            <organization>Institut Pasteur</organization>
            <organizationUrl>https://pasteur.fr</organizationUrl>
            <url>https://icy.bioimageanalysis.org/author/tmusset/</url>
        </developer>
    </developers>

    <contributors>
        <contributor>
            <name>Stéphane Dallongeville</name>
            <url>https://icy.bioimageanalysis.org/author/stef/</url>
        </contributor>
        <contributor>
            <name>Fabrice de Chaumont</name>
            <url>https://icy.bioimageanalysis.org/author/fab/</url>
        </contributor>
        <contributor>
            <name>Amandine Tournay</name>
            <url>https://icy.bioimageanalysis.org/author/amandine-tournay/</url>
        </contributor>
    </contributors>

    <mailingLists>
        <mailingList>
            <name>Icy</name>
            <post>icy.team@pasteur.fr</post>
        </mailingList>
    </mailingLists>

    <properties>
        <license.licenseName>GNU LGPLv3</license.licenseName>
        <license.copyrightOwners>Institut Pasteur</license.copyrightOwners>

        <maven-resolver.version>1.9.27</maven-resolver.version>
        <maven-resolver-impl.version>${maven-resolver.version}</maven-resolver-impl.version>
        <maven-resolver-supplier.version>${maven-resolver.version}</maven-resolver-supplier.version>
        <maven-resolver-connector-basic.version>${maven-resolver.version}</maven-resolver-connector-basic.version>
        <maven-resolver-transport-http.version>${maven-resolver.version}</maven-resolver-transport-http.version>
        <org.apache.maven.resolver.maven-resolver-impl.version>${maven-resolver-impl.version}</org.apache.maven.resolver.maven-resolver-impl.version>
        <org.apache.maven.resolver.maven-resolver-supplier.version>${maven-resolver.version}</org.apache.maven.resolver.maven-resolver-supplier.version>
        <org.apache.maven.resolver.maven-resolver-connector-basic.version>${maven-resolver.version}</org.apache.maven.resolver.maven-resolver-connector-basic.version>
        <org.apache.maven.resolver.maven-resolver-transport-http.version>${maven-resolver.version}</org.apache.maven.resolver.maven-resolver-transport-http.version>

        <maven-model-builder.version>3.9.16</maven-model-builder.version>
        <org.apache.maven.maven-model-builder.version>${maven-model-builder.version}</org.apache.maven.maven-model-builder.version>

        <plexus-utils.version>3.6.1</plexus-utils.version>
        <org.codehaus.plexus.plexus-utils.version>${plexus-utils.version}</org.codehaus.plexus.plexus-utils.version>

        <plexus-interpolation.version>1.29</plexus-interpolation.version>
        <org.codehaus.plexusplexus-interpolation.version>${plexus-interpolation.version}</org.codehaus.plexusplexus-interpolation.version>
    </properties>

    <build>
        <directory>build</directory>

        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>${build-helper-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <id>add-resource</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>add-resource</goal>
                        </goals>
                        <configuration>
                            <resources>
                                <resource>
                                    <directory>ext</directory>
                                    <targetPath>${outputDirectory}/icy</targetPath>
                                </resource>
                                <resource>
                                    <directory>.</directory>
                                    <targetPath>${outputDirectory}/icy</targetPath>
                                    <include>CHANGELOG.md</include>
                                    <include>LICENSE</include>
                                    <include>README.md</include>
                                    <include>CONTRIBUTING.md</include>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>${maven-dependency-plugin.version}</version>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <excludeGroupIds>sun.jdt,jdk.tools</excludeGroupIds>
                            <excludeArtifactIds>annotations,junit-jupiter</excludeArtifactIds>
                            <outputDirectory>${outputDirectory}/icy/lib</outputDirectory>
                            <stripVersion>${stripVersion}</stripVersion>
                            <prependGroupId>true</prependGroupId>
                            <overWriteIfNewer>true</overWriteIfNewer>
                            <excludeTransitive>false</excludeTransitive>
                            <excludeScope>provided</excludeScope>
                        </configuration>
                    </execution>
                    <execution>
                        <id>copy-icy-jar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>${project.groupId}</groupId>
                                    <artifactId>${project.artifactId}</artifactId>
                                    <version>${project.version}</version>
                                    <type>${project.packaging}</type>
                                    <outputDirectory>${outputDirectory}/icy</outputDirectory>
                                    <destFileName>icy.jar</destFileName>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <artifactId>maven-jar-plugin</artifactId>
                <version>${maven-jar-plugin.version}</version>
                <configuration>
                    <excludes>
                        <exclude>doc/doc-files</exclude>
                    </excludes>
                    <archive>
                        <manifest>
                            <classpathLayoutType>custom</classpathLayoutType>
                            <!--suppress UnresolvedMavenProperty -->
                            <customClasspathLayout>$${artifact.groupId}.$${artifact.artifactId}$${artifact.dashClassifier?}.$${artifact.extension}</customClasspathLayout>
                            <addClasspath>true</addClasspath>
                            <classpathPrefix>lib/</classpathPrefix>
                            <mainClass>fr.icy.Icy</mainClass>
                        </manifest>
                        <manifestEntries>
                            <Multi-Release>true</Multi-Release>
                        </manifestEntries>
                        <addMavenDescriptor>false</addMavenDescriptor>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <!-- Apache Batik -->
        <dependency>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-anim</artifactId>
            <version>${org.apache.xmlgraphics.batik-anim.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-awt-util</artifactId>
            <version>${org.apache.xmlgraphics.batik-awt-util.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-bridge</artifactId>
            <version>${org.apache.xmlgraphics.batik-bridge.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-css</artifactId>
            <version>${org.apache.xmlgraphics.batik-css.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-codec</artifactId>
            <version>${org.apache.xmlgraphics.batik-codec.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-constants</artifactId>
            <version>${org.apache.xmlgraphics.batik-constants.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-dom</artifactId>
            <version>${org.apache.xmlgraphics.batik-dom.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-ext</artifactId>
            <version>${org.apache.xmlgraphics.batik-ext.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-gvt</artifactId>
            <version>${org.apache.xmlgraphics.batik-gvt.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-i18n</artifactId>
            <version>${org.apache.xmlgraphics.batik-i18n.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-parser</artifactId>
            <version>${org.apache.xmlgraphics.batik-parser.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-script</artifactId>
            <version>${org.apache.xmlgraphics.batik-script.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-svg-dom</artifactId>
            <version>${org.apache.xmlgraphics.batik-svg-dom.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-svggen</artifactId>
            <version>${org.apache.xmlgraphics.batik-svggen.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-transcoder</artifactId>
            <version>${org.apache.xmlgraphics.batik-transcoder.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-util</artifactId>
            <version>${org.apache.xmlgraphics.batik-util.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-xml</artifactId>
            <version>${org.apache.xmlgraphics.batik-xml.version}</version>
        </dependency>

        <!-- Apache POI -->
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>${org.apache.poi.poi.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>${org.apache.poi.poi-ooxml.version}</version>
        </dependency>

        <!-- BioFormats -->
        <dependency>
            <groupId>ome</groupId>
            <artifactId>bio-formats_plugins</artifactId>
            <version>${ome.bio-formats_plugins.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>ome</groupId>
            <artifactId>bio-formats-tools</artifactId>
            <version>${ome.bio-formats-tools.version}</version>
        </dependency>
        <dependency>
            <groupId>ome</groupId>
            <artifactId>formats-api</artifactId>
            <version>${ome.formats-api.version}</version>
        </dependency>
        <dependency>
            <groupId>ome</groupId>
            <artifactId>formats-bsd</artifactId>
            <version>${ome.formats-bsd.version}</version>
        </dependency>
        <!--<dependency>
            <groupId>ome</groupId>
            <artifactId>formats-gpl</artifactId>
            <version>${ome.formats-gpl.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>-->
        <dependency>
            <groupId>org.openmicroscopy</groupId>
            <artifactId>ome-codecs</artifactId>
            <version>${org.openmicroscopy.ome-codecs.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openmicroscopy</groupId>
            <artifactId>ome-common</artifactId>
            <version>${org.openmicroscopy.ome-common.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openmicroscopy</groupId>
            <artifactId>ome-xml</artifactId>
            <version>${org.openmicroscopy.ome-xml.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openmicroscopy</groupId>
            <artifactId>specification</artifactId>
            <version>${org.openmicroscopy.specification.version}</version>
        </dependency>
        <!--<dependency>
            <groupId>ome</groupId>
            <artifactId>turbojpeg</artifactId>
        </dependency>-->

        <!-- EhCache -->
        <dependency>
            <groupId>org.ehcache</groupId>
            <artifactId>ehcache</artifactId>
            <version>${org.ehcache.ehcache.version}</version>
        </dependency>

        <!-- FlatLaf -->
        <dependency>
            <groupId>com.formdev</groupId>
            <artifactId>flatlaf</artifactId>
            <version>${com.formdev.flatlaf.version}</version>
        </dependency>
        <dependency>
            <groupId>com.formdev</groupId>
            <artifactId>flatlaf-extras</artifactId>
            <version>${com.formdev.flatlaf.version}</version>
        </dependency>
        <dependency>
            <groupId>com.formdev</groupId>
            <artifactId>flatlaf-swingx</artifactId>
            <version>${com.formdev.flatlaf.version}</version>
        </dependency>
        <dependency>
            <groupId>com.formdev</groupId>
            <artifactId>flatlaf-fonts-jetbrains-mono</artifactId>
            <version>${com.formdev.flatlaf-fonts-jetbrains-mono.version}</version>
        </dependency>

        <!-- ImgLib2 -->
        <dependency>
            <groupId>net.imglib2</groupId>
            <artifactId>imglib2</artifactId>
            <version>${net.imglib2.imglib2.version}</version>
        </dependency>
        <dependency>
            <groupId>net.imglib2</groupId>
            <artifactId>imglib2-algorithm</artifactId>
            <version>${net.imglib2.imglib2-algorithm.version}</version>
        </dependency>
        <dependency>
            <groupId>net.imglib2</groupId>
            <artifactId>imglib2-realtransform</artifactId>
            <version>${net.imglib2.imglib2-realtransform.version}</version>
        </dependency>

        <!-- JAI -->
        <dependency>
            <groupId>javax.media</groupId>
            <artifactId>jai-core</artifactId>
            <version>${javax.media.jai-core.version}</version>
        </dependency>
        <dependency>
            <groupId>com.sun.media</groupId>
            <artifactId>jai-codec</artifactId>
            <version>${com.sun.media.jai-codec.version}</version>
        </dependency>

        <!-- Jansi -->
        <dependency>
            <groupId>org.fusesource.jansi</groupId>
            <artifactId>jansi</artifactId>
            <version>${org.fusesource.jansi.version}</version>
        </dependency>

        <!-- Jogamp -->
        <dependency>
            <groupId>org.jogamp.jogl</groupId>
            <artifactId>jogl-all</artifactId>
            <version>${org.jogamp.jogl.jogl-all.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jogamp.jogl</groupId>
            <artifactId>jogl-all</artifactId>
            <version>${org.jogamp.jogl.jogl-all.version}</version>
            <classifier>natives-linux-amd64</classifier>
        </dependency>
        <dependency>
            <groupId>org.jogamp.jogl</groupId>
            <artifactId>jogl-all</artifactId>
            <version>${org.jogamp.jogl.jogl-all.version}</version>
            <classifier>natives-macosx-universal</classifier>
        </dependency>
        <dependency>
            <groupId>org.jogamp.jogl</groupId>
            <artifactId>jogl-all</artifactId>
            <version>${org.jogamp.jogl.jogl-all.version}</version>
            <classifier>natives-windows-amd64</classifier>
        </dependency>
        <dependency>
            <groupId>org.jogamp.gluegen</groupId>
            <artifactId>gluegen-rt</artifactId>
            <version>${org.jogamp.gluegen.gluegen-rt.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jogamp.gluegen</groupId>
            <artifactId>gluegen-rt</artifactId>
            <version>${org.jogamp.gluegen.gluegen-rt.version}</version>
            <classifier>natives-linux-amd64</classifier>
        </dependency>
        <dependency>
            <groupId>org.jogamp.gluegen</groupId>
            <artifactId>gluegen-rt</artifactId>
            <version>${org.jogamp.gluegen.gluegen-rt.version}</version>
            <classifier>natives-macosx-universal</classifier>
        </dependency>
        <dependency>
            <groupId>org.jogamp.gluegen</groupId>
            <artifactId>gluegen-rt</artifactId>
            <version>${org.jogamp.gluegen.gluegen-rt.version}</version>
            <classifier>natives-windows-amd64</classifier>
        </dependency>

        <!-- Log4j -->
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>${org.apache.logging.log4j.log4j-core.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>${org.apache.logging.log4j.log4j-api.version}</version>
        </dependency>

        <!-- Maven Resolver -->
        <dependency>
            <groupId>org.apache.maven.resolver</groupId>
            <artifactId>maven-resolver-impl</artifactId>
            <version>${org.apache.maven.resolver.maven-resolver-impl.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.maven.resolver</groupId>
            <artifactId>maven-resolver-supplier</artifactId>
            <version>${org.apache.maven.resolver.maven-resolver-supplier.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.maven.resolver</groupId>
            <artifactId>maven-resolver-connector-basic</artifactId>
            <version>${org.apache.maven.resolver.maven-resolver-connector-basic.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.maven.resolver</groupId>
            <artifactId>maven-resolver-transport-http</artifactId>
            <version>${org.apache.maven.resolver.maven-resolver-transport-http.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.maven</groupId>
            <artifactId>maven-model-builder</artifactId>
            <version>${org.apache.maven.maven-model-builder.version}</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.plexus</groupId>
            <artifactId>plexus-utils</artifactId>
            <version>${org.codehaus.plexus.plexus-utils.version}</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.plexus</groupId>
            <artifactId>plexus-interpolation</artifactId>
            <version>${org.codehaus.plexusplexus-interpolation.version}</version>
        </dependency>

        <!-- SnakeYAML -->
        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
            <version>${org.yaml.snakeyaml.version}</version>
        </dependency>

        <!-- SwingX -->
        <dependency>
            <groupId>org.swinglabs.swingx</groupId>
            <artifactId>swingx-all</artifactId>
            <version>${org.swinglabs.swingx.swingx-all.version}</version>
        </dependency>

        <dependency>
            <groupId>fr.icy.shared</groupId>
            <artifactId>vtk</artifactId>
            <version>${fr.icy.shared.vtk.version}</version>
        </dependency>
        <dependency>
            <groupId>fr.icy.shared</groupId>
            <artifactId>vtk</artifactId>
            <version>${fr.icy.shared.vtk.version}</version>
            <classifier>natives-linux-amd64</classifier>
        </dependency>
        <dependency>
            <groupId>fr.icy.shared</groupId>
            <artifactId>vtk</artifactId>
            <version>${fr.icy.shared.vtk.version}</version>
            <classifier>natives-macos-amd64</classifier>
        </dependency>
        <dependency>
            <groupId>fr.icy.shared</groupId>
            <artifactId>vtk</artifactId>
            <version>${fr.icy.shared.vtk.version}</version>
            <classifier>natives-macos-arm64</classifier>
        </dependency>
        <dependency>
            <groupId>fr.icy.shared</groupId>
            <artifactId>vtk</artifactId>
            <version>${fr.icy.shared.vtk.version}</version>
            <classifier>natives-windows-amd64</classifier>
        </dependency>
    </dependencies>
</project>