#!/bin/bash

PRG=$0
while [ -h "$PRG" ]; do
	ls=$(ls -ld "$PRG")
	link=$(expr "$ls" : '^.*-> \(.*\)$' 2>/dev/null)
	if expr "$link" : '^/' 2> /dev/null >/dev/null; then
		PRG="$link"
	else
		PRG="$(dirname "$PRG")/$link"
	fi
done
PROGDIR=$(dirname "$PRG")

cd "${PROGDIR}"/../../ || exit 11

AppPackageFolder=$(pwd)
AppResourcesFolder="${AppPackageFolder}"/Contents/Resources
AppIconPath="${AppResourcesFolder}"/icy.icns

cd "${AppPackageFolder}" || exit 11

JAVA_TARGET=21

if type -p /usr/libexec/java_home; then
    echo "Found java in java_home (macOS only)"
    _java_home=$(/usr/libexec/java_home)
elif type -p java; then
    echo found java executable in PATH
    _java=java
elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
    echo found java executable in JAVA_HOME
    _java="$JAVA_HOME/bin/java"
else
    echo "No java found"
fi

if [[ "$_java_home" ]]; then
    version=$(/usr/libexec/java_home -v $JAVA_TARGET --exec java -version 2>&1 | awk -F '"' '/version/ {print $2}')
    echo version "$version"
    if [[ "$version" > "$JAVA_TARGET" ]] || [[ "$version" -ge "$JAVA_TARGET" ]]; then
        /usr/libexec/java_home -v $JAVA_TARGET --exec java -Xdock:icon="${AppIconPath}" -Xdock:name="Icy" -jar updater.jar
    else
        echo "version is less than $JAVA_TARGET"
    fi
elif [[ "$_java" ]]; then
    version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
    echo version "$version"
    if [[ "$version" > "$JAVA_TARGET" ]] || [[ "$version" -ge "$JAVA_TARGET" ]]; then
        java -Xdock:icon="${AppIconPath}" -Xdock:name="Icy" -jar updater.jar
    else
        echo "version is less than $JAVA_TARGET"
    fi
fi

#/usr/libexec/java_home -v 21 --exec java -Xdock:icon="${AppIconPath}" -Xdock:name="Icy" -jar updater.jar