#!/usr/bin/env bash

JAVA_TARGET=21
BASEDIR=$(dirname "$0")

if type -p java; then
    echo found java executable in PATH
    _java=java
elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
    echo found java executable in JAVA_HOME
    _java="$JAVA_HOME/bin/java"
else
    echo "No java found"
fi

if [[ "$_java" ]]; then
    version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
    echo "Java version: $version"
    first_number=$(echo "$version" | cut -d '.' -f 1)
    if [[ "$first_number" -ge $JAVA_TARGET ]]; then
        java -jar "$BASEDIR"/updater.jar
    else
        echo "Version is lower than $JAVA_TARGET. Please install Java $JAVA_TARGET or greater."
    fi
fi


